// Generated from the "Vault Reference Table" sheet of the MAG Routine Composition Planner.
// value = D score for Developmental and Intermediate; adv = D score for Advanced (GymACT).
// flipping = false for handspring vaults with no salto (Developmental only allows these).
export const VAULTS = [
  {"id": "101", "name": "Hdspr. tucked, 1/2t. (Cuervo t.)", "eg": "I", "value": 2.4, "adv": 2.4, "flipping": true},
  {"id": "102", "name": "Hdspr. tucked 1/1t.", "eg": "I", "value": 2.8, "adv": 2.8, "flipping": true},
  {"id": "103", "name": "Hdspr. tucked 3/2t. (Kroll)", "eg": "I", "value": 3.2, "adv": 3.2, "flipping": true},
  {"id": "104", "name": "Hdspr. tucked 2/1t. (Canbas)", "eg": "I", "value": 3.6, "adv": 3.6, "flipping": true},
  {"id": "105", "name": "Hdspr. piked, 1/2t. (Cuervo p.)", "eg": "I", "value": 2.8, "adv": 3.6, "flipping": true},
  {"id": "108", "name": "Hdspr. piked 1/1t.", "eg": "I", "value": 3.2, "adv": 4.4, "flipping": true},
  {"id": "109", "name": "Hdspr. piked 3/2t.", "eg": "I", "value": 3.6, "adv": 4.8, "flipping": true},
  {"id": "111", "name": "Hdspr. str. 1/2t. (Cuervo str.)", "eg": "I", "value": 3.6, "adv": 4.0, "flipping": true},
  {"id": "114", "name": "Hdspr. str. 1/1t. (Cuervo str 1/2t.)", "eg": "I", "value": 4.0, "adv": 4.4, "flipping": true},
  {"id": "115", "name": "Hdspr. str 3/2t. (Lou Yun)", "eg": "I", "value": 4.4, "adv": 4.8, "flipping": true},
  {"id": "116", "name": "Hdspr. str. 2/1t. (Cuervo str. 3/2t.)", "eg": "I", "value": 4.8, "adv": 5.2, "flipping": true},
  {"id": "117", "name": "Hdspr. str. 5/2t. (Yeo 2)", "eg": "I", "value": 5.2, "adv": 5.6, "flipping": true},
  {"id": "118", "name": "Hdspr. str 3/1t. (Yang Hak Seon)", "eg": "I", "value": 5.6, "adv": 6.0, "flipping": true},
  {"id": "119", "name": "Tsuk tucked 1/1t. (Kasamatsu)", "eg": "I", "value": 2.4, "adv": 2.4, "flipping": true},
  {"id": "120", "name": "Tsuk tucked 3/2t.", "eg": "I", "value": 2.8, "adv": 2.8, "flipping": true},
  {"id": "121", "name": "Tsuk tucked 2/1t. (Barbieri)", "eg": "I", "value": 3.2, "adv": 3.2, "flipping": true},
  {"id": "122", "name": "Tsuk tucked 5/2 t.", "eg": "I", "value": 3.6, "adv": 3.6, "flipping": true},
  {"id": "125", "name": "Tsuk str. 1/1 t.", "eg": "I", "value": 3.6, "adv": 3.6, "flipping": true},
  {"id": "126", "name": "Tsuk str. 3/2 t.", "eg": "I", "value": 4.0, "adv": 4.0, "flipping": true},
  {"id": "127", "name": "Tsuk str. 2/1 t. (Akopian)", "eg": "I", "value": 4.4, "adv": 4.4, "flipping": true},
  {"id": "131", "name": "Tsuk str. 5/2 t. (Driggs)", "eg": "I", "value": 4.8, "adv": 4.8, "flipping": true},
  {"id": "132", "name": "Tsuk str. 3/1 t. (Lopez)", "eg": "I", "value": 5.2, "adv": 5.2, "flipping": true},
  {"id": "133", "name": "Tsuk str. 7/2 t. (Yonekura)", "eg": "I", "value": 5.6, "adv": 5.6, "flipping": true},
  {"id": "201", "name": "Hdspr.", "eg": "II", "value": 1.2, "adv": 1.2, "flipping": false},
  {"id": "202", "name": "Hdspr. 1/2t.", "eg": "II", "value": 1.4, "adv": 1.4, "flipping": false},
  {"id": "203", "name": "Hdspr. 1/1t.", "eg": "II", "value": 1.6, "adv": 1.6, "flipping": false},
  {"id": "204", "name": "Hdspr. 3/2t.", "eg": "II", "value": 1.8, "adv": 1.8, "flipping": false},
  {"id": "205", "name": "Hdspr. 2/1t.", "eg": "II", "value": 2.0, "adv": 2.0, "flipping": false},
  {"id": "206", "name": "Hdspr. 5/2 t. (Tsygankov)", "eg": "II", "value": 2.2, "adv": 2.2, "flipping": false},
  {"id": "207", "name": "Hdspr. tucked", "eg": "II", "value": 2.0, "adv": 2.0, "flipping": true},
  {"id": "213", "name": "Hdspr. piked", "eg": "II", "value": 2.4, "adv": 2.8, "flipping": true},
  {"id": "219", "name": "Hdspr. str.", "eg": "II", "value": 3.2, "adv": 3.8, "flipping": true},
  {"id": "225", "name": "Hdspr. dbl. salto tucked (Roche)", "eg": "II", "value": 4.8, "adv": 5.2, "flipping": true},
  {"id": "226", "name": "Roche 1/2t. (Dragulescu)", "eg": "II", "value": 5.2, "adv": 5.6, "flipping": true},
  {"id": "228", "name": "Hdspr. 1/2t. bwd (Zimmerman)", "eg": "II", "value": 5.2, "adv": 5.6, "flipping": true},
  {"id": "231", "name": "Hdspr. dbl. piked (Blanik)", "eg": "II", "value": 5.2, "adv": 5.6, "flipping": true},
  {"id": "232", "name": "Dragulescu piked (Ri Se Gwang2)", "eg": "II", "value": 5.6, "adv": 6.0, "flipping": true},
  {"id": "301", "name": "Hdspr. str. 1/4t.", "eg": "III", "value": 1.2, "adv": 1.2, "flipping": false},
  {"id": "302", "name": "Hdspr. 3/4t.", "eg": "III", "value": 1.4, "adv": 1.4, "flipping": false},
  {"id": "303", "name": "Hdspr. sw. 5/4t.", "eg": "III", "value": 1.6, "adv": 1.6, "flipping": false},
  {"id": "307", "name": "Tsuk. Tucked. (Tsukahara)", "eg": "III", "value": 1.8, "adv": 1.8, "flipping": true},
  {"id": "308", "name": "Tsuk. piked", "eg": "III", "value": 1.9, "adv": 1.9, "flipping": true},
  {"id": "309", "name": "Tsuk. tucked 1/2t.", "eg": "III", "value": 2.0, "adv": 2.0, "flipping": true},
  {"id": "313", "name": "Tsuk str.", "eg": "III", "value": 2.8, "adv": 2.8, "flipping": true},
  {"id": "318", "name": "Tsuk. str. 1/2t.", "eg": "III", "value": 3.2, "adv": 3.2, "flipping": true},
  {"id": "319", "name": "Tsuk. dbl. tucked (Yeo)", "eg": "III", "value": 4.8, "adv": 4.8, "flipping": true},
  {"id": "320", "name": "Tsuk. dbl. piked (Lu Yu Fu)", "eg": "III", "value": 5.2, "adv": 5.2, "flipping": true},
  {"id": "321", "name": "Tsuk. dbl. 1/1t. (Ri Se Gwang)", "eg": "III", "value": 5.6, "adv": 5.6, "flipping": true},
  {"id": "401", "name": "Yur. tucked 1/2t.", "eg": "IV", "value": 2.4, "adv": 2.4, "flipping": true},
  {"id": "402", "name": "Yur. tucked 3/2t.", "eg": "IV", "value": 2.8, "adv": 2.8, "flipping": true},
  {"id": "403", "name": "Yur. tucked 2/1t.", "eg": "IV", "value": 3.2, "adv": 3.2, "flipping": true},
  {"id": "404", "name": "Yur. str. 1/1t.", "eg": "IV", "value": 3.6, "adv": 3.6, "flipping": true},
  {"id": "405", "name": "Yur. str. 3/2t.", "eg": "IV", "value": 4.0, "adv": 4.0, "flipping": true},
  {"id": "406", "name": "Yur. str. 2/1t.", "eg": "IV", "value": 4.4, "adv": 4.4, "flipping": true},
  {"id": "407", "name": "Yur. str. 5/2t. (Shewfelt)", "eg": "IV", "value": 4.8, "adv": 4.8, "flipping": true},
  {"id": "408", "name": "Yur. str. 3/1t. (Shirai 1/KIM Hee Hoon)", "eg": "IV", "value": 5.2, "adv": 5.2, "flipping": true},
  {"id": "409", "name": "Yur. str. 7/2t. (Shirai 2)", "eg": "IV", "value": 5.6, "adv": 5.6, "flipping": true},
  {"id": "413", "name": "Rou. off. 1/2t. tucked 1/2t.", "eg": "IV", "value": 0.8, "adv": 0.8, "flipping": true},
  {"id": "414", "name": "Rou. off. 1/2t. piked. 1/2t. (Nemov)", "eg": "IV", "value": 1.0, "adv": 1.0, "flipping": true},
  {"id": "415", "name": "Rou. off, 1/2t. str. 1/2t. (Hutcheon)", "eg": "IV", "value": 1.8, "adv": 1.8, "flipping": true},
  {"id": "416", "name": "Rou. off, 1/2t. str. 1/1t.", "eg": "IV", "value": 3.2, "adv": 3.2, "flipping": true},
  {"id": "417", "name": "Rou. off, 1/2t. str. 3/2t.", "eg": "IV", "value": 3.6, "adv": 3.6, "flipping": true},
  {"id": "419", "name": "Rou. off, 1/2t. str. 2/1t.", "eg": "IV", "value": 5.0, "adv": 5.0, "flipping": true},
  {"id": "420", "name": "Yur. dbl. str. 5/2t. (Li Xiao Peng)", "eg": "IV", "value": 5.4, "adv": 5.4, "flipping": true},
  {"id": "501", "name": "Rou. off. hdspr. bwd", "eg": "V", "value": 1.2, "adv": 1.2, "flipping": false},
  {"id": "502", "name": "Rou. off, hdspr. bwd. 1/2t.", "eg": "V", "value": 1.4, "adv": 1.4, "flipping": false},
  {"id": "503", "name": "Rou. off, hdspr. bwd. 1/1t.", "eg": "V", "value": 1.6, "adv": 1.6, "flipping": false},
  {"id": "507", "name": "Rou. off, tucked salto (Yurchenko)", "eg": "V", "value": 1.8, "adv": 1.8, "flipping": true},
  {"id": "508", "name": "Yur. tucked 1/2t.", "eg": "V", "value": 2.0, "adv": 2.0, "flipping": true},
  {"id": "509", "name": "Yur. piked", "eg": "V", "value": 2.0, "adv": 2.0, "flipping": true},
  {"id": "511", "name": "Yur. str.", "eg": "V", "value": 2.4, "adv": 2.4, "flipping": true},
  {"id": "512", "name": "Yur. str. 1/2t.", "eg": "V", "value": 2.8, "adv": 2.8, "flipping": true},
  {"id": "513", "name": "Rou. off, 1/2t. hdspr.", "eg": "V", "value": 1.4, "adv": 1.4, "flipping": false},
  {"id": "514", "name": "Rou. off, 1/2t. hdspr. 1/2t.", "eg": "V", "value": 1.6, "adv": 1.6, "flipping": false},
  {"id": "515", "name": "Rou. off, 1/2t. hdspr. 1/1t.", "eg": "V", "value": 1.8, "adv": 1.8, "flipping": false},
  {"id": "516", "name": "Rou. off, 1/2t. tucked", "eg": "V", "value": 2.2, "adv": 2.2, "flipping": true},
  {"id": "517", "name": "Rou. off, 1/2t. piked", "eg": "V", "value": 2.6, "adv": 2.6, "flipping": true},
  {"id": "518", "name": "Rou. off, 1/2t. str.", "eg": "V", "value": 3.4, "adv": 3.4, "flipping": true},
  {"id": "519", "name": "Yur. dbl. tucked (Melissanidis)", "eg": "V", "value": 4.8, "adv": 4.8, "flipping": true},
  {"id": "520", "name": "Yur. dbl. piked (Yang Wei)", "eg": "V", "value": 5.2, "adv": 5.2, "flipping": true},
  {"id": "521", "name": "Rou. off, 1/2t. dbl. salto", "eg": "V", "value": 5.0, "adv": 5.0, "flipping": true},
];
