"""Builds js/skills.js, the skill list behind the skill search, from:

  WG skills:  skills_verified.json from the FIG MAG CoP 2025-2028 extractor
              (Dropbox: Misc/Gymnastics/Reference/gym_skill_extract)
  UCG skills: every skill box in the UCG MAG Code of Points master
              (Dropbox: Misc/Gymnastics/UCG/Code of Points/MAG/UCG MAG CoP.svg),
              read with that repo's tools (needs Inkscape, as they do)

Run after the UCG CoP gets new skills (or a new WG CoP is extracted):
    python tools/build_skills.py
Paths can be overridden with --wg and --cop (the Code of Points repo folder).
Vaults aren't included: the vault picker uses js/vaults.js.
"""
import argparse
import json
import os
import re
import sys

DROPBOX = os.path.expanduser(r"~/Steinsharpe Dropbox/Nate Sharpe/Documents/Misc/Gymnastics")
WG_DEFAULT = os.path.join(DROPBOX, "Reference", "gym_skill_extract", "skills_verified.json")
COP_DEFAULT = os.path.join(DROPBOX, "UCG", "Code of Points")
OUT = os.path.join(os.path.dirname(__file__), "..", "js", "skills.js")

APPS = ["FX", "PH", "SR", "PB", "HB"]
ROMAN = {"I": 1, "II": 2, "III": 3, "IV": 4}
# Drawing labels inside some UCG boxes, not part of the skill name.
DROP = re.compile(r"^\((DSA|DSB|Circle in (cross|side) support)\)$|^(A|B|C|D|Ga)$")


def wg_skills(path):
    out = []
    for s in json.load(open(path, encoding="utf-8")):
        if s["apparatus"] not in APPS:
            continue
        out.append({
            "id": f"WG-{s['apparatus']}-{s['element_group']}-{s['number']}",  # FIG numbers restart in each EG
            "app": s["apparatus"].lower(),
            "name": " ".join(s["description"].split()),
            "eponym": s["eponym"] or "",
            "value": s["value"].split("=")[0],
            "eg": ROMAN.get(s["element_group"]),
            "src": "WG",
            "note": "",
        })
    return out


def ucg_skills(cop_dir):
    sys.path.insert(0, os.path.join(cop_dir, "tools"))
    from cop_skills import CoP, APPARATUS_PAGES, SVG
    from paths import MAG_SVG

    cop = CoP(MAG_SVG)
    out = []
    for app in APPS:
        res, _ = cop.skills(app)
        for r in res:
            lines = []
            for el in cop.cells[r["at"]]["content"]:
                for t in el.iter(SVG + "text"):
                    style = (t.get("style") or "") + "".join(x.get("style") or "" for x in t.iter())
                    if "Greed" in style:  # value / EG lettering
                        continue
                    for line in [x for x in t if x.tag == SVG + "tspan"] or [t]:
                        s = " ".join("".join(line.itertext()).split())
                        if s:
                            lines.append(s)
            name, note, eponyms, in_note = [], [], [], False
            for s in lines:
                if DROP.match(s):
                    continue
                if s.startswith("Note:") or s.startswith("(same box"):
                    in_note = True
                m = re.fullmatch(r"\(([A-Z][A-Za-z.' -]+(?: \d)?)\)", s)  # (Batta), (Sharpe 2)
                if m and not s.startswith("(same box"):
                    eponyms.append(m.group(1))
                    in_note = False
                elif in_note:
                    note.append(s)
                else:
                    name.append(s)
            value = r["value"]
            out.append({
                # Ids are saved with routines, so they come from the name, not the box position.
                "id": f"UCG-{app}-" + re.sub(r"[^a-z0-9]+", "-", " ".join(name + eponyms).lower()).strip("-")[:60],
                "app": app.lower(),
                "name": " ".join(name),
                "eponym": " / ".join(eponyms),
                "value": "Sub-A" if value.upper().startswith("SUB") else value.upper(),
                "eg": ROMAN.get(r["eg"]),
                "src": "UCG",
                "note": " ".join(note).replace("Note: ", ""),
            })
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--wg", default=WG_DEFAULT)
    ap.add_argument("--cop", default=COP_DEFAULT)
    a = ap.parse_args()
    skills = ucg_skills(a.cop) + wg_skills(a.wg)
    rows = ",\n".join("  " + json.dumps(s, ensure_ascii=False) for s in skills)
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("// Generated by tools/build_skills.py: UCG MAG CoP skills, then WG (FIG MAG CoP 2025-2028) skills.\n")
        f.write("// eg: element group 1-4, or null (no EG bonus). value: A-J or Sub-A.\n")
        f.write(f"export const SKILLS = [\n{rows}\n];\n")
    counts = {}
    for s in skills:
        counts[s["src"]] = counts.get(s["src"], 0) + 1
    print(f"wrote {os.path.normpath(OUT)}: {counts}")


if __name__ == "__main__":
    main()
